<div id="homesection1">
	<p id="home1">Greetings traveller. Believe the mirage, you have stumbled into one of the last few oases of poetry in the burning desert of modern life. It should seem ironic that the use of the internet, to which we can attribute the loss of appreciation of your average sonnet, may end up being the saviour of discussion on some of poetry's true gems.</p>
	<p id="home2">How often have you read poetry? Better yet, how often you do you get the chance to read? It's not common to come home from a hard day's work at the office and crack open a tome of poems by the fireside. Nor is it common to sit beside your young's bedside filling their mind with the beautiful imagery that has led you in the search throughout your life to find more and more poetry.</p>
	<p id="home3">With the advent of this website, we intend to enable people from around the world to enjoy poetry whenever they have access to the internet and perhaps some artistic avenues that weren't previously obvious to them. Annotations have always been an important part of poetry and we see no reason why that has to change. Or why it should be limited to certain individuals.</p>
	<p id="home4">The premise is simple. Any line you read can be dissected by you to your heart's content and then anyone will be able to see what your thoughts on the matter are. The fact that no personal information is taken when annotating is a thought attributed to the idea that none of us are as smart as all of us. When you take into consideration that a particularlly thoughtful annotation could have been made by a medical consultant or gift card maker or a landscaper or anyone you see in your everyday life.</p>
	<p id="home5">All types of poetry are welcome here, whether they be in a traditional format, more modern or even haikus, there's room for all of them. And if you're feeling daring enough, why not submit one of your own creations? You may inspire others just like you yourself have been inspired. But enough of all that. Let us continue the journey and feast our eyes and open our ears to more beautiful imagery than we never dreamed possible.</p>
</div>

<div id="homesection2">
	<p>Cian Jordan, Stephen Leonard</p>
</div>

<br>

<div id="homesection3">
	<img src="images/poetry.jpg" id="handwriting">
</div>

<div id="homesection4">
	<a href="/poems" id="Takeme">Take me to the poems!</a>
</div>
