<div id="poemcontainer">

	<div id="content">
		<br>
		<h2><?php echo $this->poem->name ?></h2>
		<?php if($this->poem->poet): ?>
			by <?php echo $this->poem->poet; ?><br>
		<?php endif; ?>
		
		<br/> 
		
		<?php foreach($this->poem->lines as $id => $line): ?>
			<span id="line<?php echo $id+1; ?>" class="line" onclick="underline(<?php echo $id+1; ?>)"><?php echo $id+1; ?>. <?php echo $line['text']; ?><br/></span>
		<?php endforeach; ?>
	</div>

	<br/>

	<div id="poemform">

		<form id="Anontate" method="post">

			Select the line you wish to annotate:

			<select name="line" id="linebox" onchange="linecol()">

				<option></option>
				<?php for($i = 1; $i <= count($this->poem->lines); $i++): ?>
					<option value="<?php echo $i; ?>"><?php echo $i; ?></option>
				<?php endfor; ?>
			</select>

			<br/>

			<textarea class="annotbox" name="text" required placeholder="Annotate to your heart's content."></textarea>
			
			<br/>

			<input type="submit" value="Submit">

		</form>


	</div>

</div>


<div id="commentbox">

	<span id="comment0">Click on a line to see some annotations.</span>
	<?php for($i = 1; $i <= count($this->poem->lines); $i++): ?>
		<span id="comment<?php echo $i; ?>">
			<?php 
			
			if($annotation = $this->poem->annotations->get_random_annotation($i)) {
				echo $this->escape($annotation);
			} else {
				echo "There are no annotations for this line";
			}
					
			?>
		</span>
	<?php endfor;?>
	
</div>
